package constant

//var (
//	CannotConnectDB                 = "Cannot connect to database"
//	DataBaseCannotBeCorrectlyClosed = "Data base cannot be correctly closed"
//	DataParseError                  = "Data parse error"
//	JSONParseError                  = "JSON parse error"
//	UnsupportedMediaType            = "Unsupported media type"
//	FileParseError                  = "File parse error"
//	FileSaveError                   = "File save error"
//	DataBaseSaveError               = "Data base save error"
//	DataBaseQueryError              = "Data base query error"
//	DataBaseDeleteError             = "Data base delete error"
//	DataBaseUpdateError             = "Data base update error"
//	ConfirmUserPassWordNotSame      = "User confirm password is not correct"
//	RegisterUserNameLengthError     = "the length of user's name has error"
//	UserNameExisted                 = "the user name is existed"
//	PasswordEncryptError            = "Password encrypt error"
//	DataNotExist                    = "Data not exist"
//	PasswordError                   = "Password error"
//	TokenExpired                    = "token expired"
//	TokenInvalid                    = "token invalid"
//	TokenClaimsError                = "token claims error"
//	TokenAuthorityHeaderMissed      = "token authority header missed"
//	ContextError                    = "context error"
//	TypeAssertionError              = "type assertion error"
//	DataCannotModify                = "data cannot be modified"
//	DataCannotEmpty                 = "data cannot be empty"
//	UserEmailError                  = "user's email has error"
//	DataLogicError                  = "data logic error"
//)

var (
	CannotConnectDB                 = "无法连接到数据库"
	CannotQueryPositionInfo         = "无法查询到位置信息"
	CannotQueryWeatherInfo          = "无法查询到天气信息"
	CannotQueryAirQualityInfo       = "无法查询到空气质量信息"
	InvalidParameter                = "参数错误"
	SystemError                     = "系统错误"
	DataBaseCannotBeCorrectlyClosed = "数据库无法正确关闭"
	DataParseError                  = "数据解析错误"
	JSONParseError                  = "JSON解析错误"
	UnsupportedMediaType            = "不支持的媒体类型"
	FileParseError                  = "文件解析错误"
	FileSaveError                   = "文件保存错误"
	DataBaseSaveError               = "数据库保存错误"
	DataBaseQueryError              = "数据库查询错误"
	DataBaseDeleteError             = "数据库删除错误"
	DataBaseUpdateError             = "数据库更新错误"
	ConfirmUserPassWordNotSame      = "用户确认密码不正确"
	RegisterUserNameLengthError     = "用户名长度错误"
	UserNameExisted                 = "用户名已存在"
	PasswordEncryptError            = "密码加密错误"
	DataNotExist                    = "数据不存在"
	PasswordError                   = "密码错误"
	TokenExpired                    = "令牌过期"
	TokenInvalid                    = "无效的令牌"
	TokenClaimsError                = "令牌声明错误"
	TokenAuthorityHeaderMissed      = "缺少令牌权限头"
	ContextError                    = "上下文错误"
	TypeAssertionError              = "类型断言错误"
	DataCannotModify                = "数据无法修改"
	DataCannotEmpty                 = "数据不能为空"
	UserEmailError                  = "用户邮箱错误"
	DataLogicError                  = "数据逻辑错误"
)
