version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_haze_detection
    environment:
      MYSQL_ROOT_PASSWORD: zyy_lhx_yjr
      MYSQL_DATABASE: haze_detection
      MYSQL_USER: zly
      MYSQL_PASSWORD: zyy_lhx_yjr
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    restart: unless-stopped

#volumes:
#  db_data:
